### ISSUE TITLE
Virgin Cable UK - Sky Arts HD Swap

### ISSUE THREAD

**Issue by chenks** [oe-alliance/AutoBouquetsMaker#124]
123 needs to be swapped with 156
previously was swapped but no longer being swapped after recent channel changes.

123 Sky Arts
156 Sky Arts HD

**Comment by AbuBaniaz** [comment]
Before I make any more changes, can you please do the following:
Remove any mix files or any other customisations (add .bak at the end of the filenames). Disable the swap in ABM and then run ABM again. Please attach the EXAMPLe file that is created in the custom folder so that we can see all the ones that need to be edited.

Best to do it in one go.

**Comment by chenks** [comment]
i don't use any custommix files at the moment.
it's a clean ABM with just HD swap enabled.

however, here is the file requested with HD swap turned off.

[EXAMPLE_hd_cable_uk_virgin_CustomLCN.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/3687536/EXAMPLE_hd_cable_uk_virgin_CustomLCN.zip)

**Comment by AbuBaniaz** [comment]
Thanks. Done
