### ISSUE TITLE
PICK tv UK

### ISSUE THREAD

**Issue by escortrs** [oe-alliance/AutoBouquetsMaker#149]
Hello,

Thank you for all the hard work but Seems to be a problem with PICK tv channel UK, freesat channel 144 and sky channel number 159, have updated to latest AutoBouquetsMaker and have run a scan, now PICK channel is being place in the wrong place right down the bottom of the "All Channels" bouquet and does not show in the "Entertainment" bouquet.

Many thanks.

edit....  possible transponder change for PICK and PICK+1 recently or due very soon.

**Comment by AbuBaniaz** [comment]
As with the other issue you raised, we don't add the channels. The only exception is if it is a "hack". The provider/broadcaster adds the details to the data stream. The only thing we did was massage the name so that HD version has HD in name and also specify the swaps.

Please start a thread on the forum with your debug log so that we can assist you with your problem. There are too many variables for us to start guessing what options you have set.

Transponder in use does not make a difference to the numerical position of the official channel. Nor does it matter unless we need to whitelist a channel.

**Comment by escortrs** [comment]
hello AbuBaniaz

where can I find the forum for AutoBouquetsMaker?

Thanks

**Comment by AbuBaniaz** [comment]
ABM was made by the ViX team. We are on world of satellite. I regularly visit linuxsat, pli, dw and tk.


If you use IPTV, make sure you remove any  sensitive details before you upload your debug log.
