### ISSUE TITLE
Crash AutoBouquetsMaker on scan!

### ISSUE THREAD

**Issue by m0807c** [oe-alliance/AutoBouquetsMaker#175]
Hi Oe-Alliance I get crash on scan any fix? Greeting [enigma2_crash_1606773330.log](https://github.com/oe-alliance/AutoBouquetsMaker/files/5618995/enigma2_crash_1606773330.log)
[](url)

**Comment by AbuBaniaz** [comment]
Just for reference purposes
```
[-] Traceback (most recent call last):
[-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/scanner/main.py", line 486, in doScan
[-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/scanner/manager.py", line 223, in read
[-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/scanner/dvbscanner.py", line 256, in updateTransponders
[-] NameError: global name 'itervalues' is not defined
```

**Comment by m0807c** [comment]
Its software bug? or I must post log of ABM? I use OpenATV 6.4.

**Comment by m0807c** [comment]
![20201203_095115](https://user-images.githubusercontent.com/75279561/101098012-7d79e480-35c2-11eb-8638-e9b4718e57a2.jpg)
This is what I get :-(

**Comment by morpheus883** [comment]
Uhm, maybe it's due to the fact that, on 13°E, Tivusat and Sky Italia are changing Transponder Systems and Modulations making the ABM scan difficult or impossible...

**Comment by s3n0** [comment]
It is a BUG... please see my comment, on the last commit:
https://github.com/oe-alliance/AutoBouquetsMaker/commit/e5babb95d8fc9be30334e0820ca55c9826c2b2f4#diff-8f207dd4349012263f0add852eeeb86b230d76dcfa4b95e7a7300a2cf791d298

**Comment by morpheus883** [comment]
Hi s3n0,

compliments for your deep analysis and for your huge knowledge of strict differences between Python 2.x and 3.

Well done,

morph

________________________________

**Comment by morpheus883** [comment]
Probably, due to this issue, the plugin can't parse correctly data...

If it can help, here following my error log while I was running ABM on MEO/NOS (30°W):

`[eDVBScan] the current channel's ID was not corrected - not adding channel.
[eDVBScan] the current channel's ID was not corrected - not adding channel.
[eDVBScan] the current channel's ID was not corrected - not adding channel.
[eDVBScan] the current channel's ID was not corrected - not adding channel.
[eDVBScan] the current channel's ID was not corrected - not adding channel.
[eDVBScan] the current channel's ID was not corrected - not adding channel.
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/scanner/main.py", line 516, in doScan
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/scanner/manager.py", line 223, in read
KeyError: 'hd_49165'`

**Comment by s3n0** [comment]
@morpheus883 : 

You can try to undo the last commit. So you change the file in your set-top box to the previous file - as I described in the discussion on OpenATV: https://www.opena.tv/english-section/54279-crash-autobouquetsmaker-scan.html#post457949 You'll see if it helps or not.

Unfortunately, I don't own a set-top box on which the alpha build version of OpenATV 6.5 would work - with Python 3. So I can't test and debug the functionality in Python 3 and also in Python 2 under Enigma. I only own Formuler F4 Turbo and Vu+ Solo SE V2 set-top boxes.

**Comment by morpheus883** [comment]
Hi again,

I would like to do it but, unfortunately I'm at work now....

Maybe someone else can do it...

Anyway, to me, there are other issues related to changes on TP/Sats and some of reference channels (with NIT/BAT Data) are now changed.

ciao,

morph

________________________________

**Comment by patsavatv** [comment]
Hello
Use with ATV 6.4 on Vu + Duo 4K SE
Also crash.
Error on a file in the folder "scanner"
I retrieved an October 31th backup of the full folder (scanner) and copied that folder to the decoder. No more crashes since. So there is a problem with one of the files!
File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/scanner
[scanner.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/5643681/scanner.zip)

**Comment by s3n0** [comment]
Unfortunately, the last commit has already been approved. A "revert" must be done in the master branch or another fix must be added :). I have no way to test it. So I can't even try to fix it (without trying it). Theoretically, what I wrote in the comment below the last commit "dvbscanner.py handle itervalues for python 2/3" should help.

**Comment by m0807c** [comment]
Its fixed big thanx to s3n0 and others ;-)

**Comment by s3n0** [comment]
Well, it's not fixed yet :). 

There is still an error in the source code yet.

I clicked revert the changes in this file, but I don't know if it will pass. The author of this change (of this "commit") should take care of the adjustment correctly. He should modify the source code to work. It could also be edited according to my example, which I gave in my comments on this particular "commit". However, I'm not sure because I don't know what the dictionary variable contains and I also don't have a device running some Enigma / Python3 firmware (alpha version of OpenATV for example).

**Comment by Huevos** [comment]
https://github.com/oe-alliance/AutoBouquetsMaker/commit/691635f5f1dd9475ee3214bf47906d24d55e3215

Please test.

**Comment by morpheus883** [comment]
Now it works: problem seems solved...
About 13°E: Sky Italy provider has wrong parameters....

**Comment by Huevos** [comment]
Please try:
https://github.com/oe-alliance/AutoBouquetsMaker/commit/8a36c0a3c8fbddff5701251c0e200b70dec7119c

**Comment by m0807c** [comment]
Hi Huevous please add under Show DVB-T frequency finder support for DVB-T2 265 HEVC !

**Comment by Huevos** [comment]
265 has nothing to do with transponder parameters. What problem are you having? Please be specific.

**Comment by JoaoSobral** [comment]
Hi,

I am also getting the same crash with Meo.  My log below.

[enigma2_crash_1607637027.log](https://github.com/oe-alliance/AutoBouquetsMaker/files/5676228/enigma2_crash_1607637027.log)

**Comment by JoaoSobral** [comment]
@s3n0 @m0807c could you be so kind  to provide me the dvbscanner.pyo with the fix? I love to try on my system.

Thanks

**Comment by AbuBaniaz** [comment]
```
Pure2 Enigma2 crash log
crashdate=Thu Dec 10 22:50:27 2020
compiledate=Dec  3 2020
sourcedate=2020-11-30
branch=6.5
```
You need to use an image newer than 5th December which will have the fixed file. Otherwise uninstall then reinstall the plugin.
The crash was fixed on 5th December.

https://github.com/oe-alliance/AutoBouquetsMaker/commit/691635f5f1dd9475ee3214bf47906d24d55e3215

I will close the issue now.

**Comment by AbuBaniaz** [comment]
@JoaoSobral 
PurE2 have updated their images.

**Comment by JoaoSobral** [comment]
@AbuBaniaz  thanks. I will try later. 👍
