### ISSUE TITLE
problemm UPC DIGI 1W  AutoBouquetsMaker 2,4 

### ISSUE THREAD

**Issue by mar1010** [oe-alliance/AutoBouquetsMaker#18]
Can you fix it.

problem  problem

The UPC DIGI 1W channel list is not generated correctly by AutoBouquetsMaker 2,4

dreambox520 dreambox 800HD open atv 

Can you fix it  problem????

**Comment by AbuBaniaz** [comment]
For us to be able to fix it, we would need to have a debug log of you running ABM.

You say it is wrong, but what is correct so that we can compare? It must be an official list, not a set of bouquets created by someone. Please provide a link to an official provider list.

**Comment by mar1010** [comment]
Ok 13e 19,2e 23,5e all Ok.
Problém all western 1W UPC ,Digi,Canal digi

**Comment by mar1010** [comment]
ABM  VU+. ,It works ok.(UPC,Digi 1W)

**Comment by AbuBaniaz** [comment]
Sorry, the information you provided is not very useful.

**Comment by AbuBaniaz** [comment]
Are there any more details that we can compare with please? Must be an official list.

**Comment by mar1010** [comment]
The problem was not 1W does not work.
When set as 0.8W and it works.  ok 

AutoBouquetsMaker 2,4 -2,5  OK

**Comment by AbuBaniaz** [comment]
I am struggling to fully understand what you are trying to say. Please explain in more detail.

That being said,
There is an issue with what position people/image teams give that satellite.
The data on the SI tables and the provider website calls it 1w.
We changed the satellite.xml file so that 0.8w was now called 1w 
Most image teams still call it 0.8w so we reverted it back to 0.8w

If your satellites.xml file does not have 0.8w, ABM will not work for the providers on 0.8w.

If there is no problem, please close the issue. If there is a problem, please try to say in a way we can understand better. If we don't understand, we can't work together.

**Comment by mar1010** [comment]
Yes exactly .
When tuning is set to 1 w so it does not work UPC DIGI.
 When I set it to 0.8 w tuning it works good UPC DIGI. 
AutoBouquetsMaker 2.4 -2.5 works OK.
Thank you.
