### ISSUE TITLE
Request from OpenSPA, not issue

### ISSUE THREAD

**Issue by OpenSPA** [oe-alliance/AutoBouquetsMaker#20]
Plugin doesn't work with OpenSPA image, but with small changes we get it working. Changes are included in setup.py file. We add these lines into class AutoBouquetsMaker_ProvidersSetup : 

def keyLeft(self):
    ConfigListScreen.keyLeft(self)
    self.changedEntry()

  def keyRight(self):
    ConfigListScreen.keyRight(self)
    self.changedEntry()

Is there any problem to include this lines into your plugin?

[setup.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/778520/setup.zip)

**Comment by Ev0-BH** [comment]
slightly off topic, but do you have any plans to commit your kodi 17 code to the oe-a git ?

**Comment by Huevos** [comment]
- if len(self.providers[provider]["bouquets"]) > 0:
+ if "bouquets" in self.providers[provider]:

What is the purpose of that. "bouquets" is always present, so that test is doing nothing.

See here: https://github.com/oe-alliance/AutoBouquetsMaker/blob/master/AutoBouquetsMaker/src/scanner/providers.py#L69

**Comment by Huevos** [comment]
> Is there any problem to include this lines into your plugin?

I've tried the above change and it causes the provider's screen to run slow in other images. Need to understand why OpenSPA is not sending the onchange.

**Comment by atvcaptain** [comment]
use boxbranding 
if openspa; then
    bla bla
else:
  old way

**Comment by AbuBaniaz** [comment]
Only the configuration is affected. Entering the values in settings file works. As ABM works on other images, would it not be better to look at the config issue? Issue could affect all other plugins too. So, instead of patching all plugins that do not work on Openspa, make Openspa work better with all plugins.

If that is not possible, then changes will have to be made to ABM provided they do not negatively affect it.

**Comment by Huevos** [comment]
We don't use boxbranding in ABM at the moment.

If we add that it will have to be in a try/except so the plugin continues to work in other images, i.e. OpenPLi, Blackhole, etc.

**Comment by OpenSPA** [comment]
I understand comments, but we don't find why is not working in our image. We continue searching why don't send the onchange. Is logical to adapt OpenSPA if plugin works in all other images, we know, but we requested this because it works with those easy lines. If it works bad in other images, no problem, we will wait until we find the issue.

@Ev0-BH 
I don't understand this off-topic, do you can help me with ABM? Kodi is planned to be uploaded, but we request patience.

**Comment by AbuBaniaz** [comment]
Resolved with this
https://github.com/oe-alliance/AutoBouquetsMaker/commit/bfd670cd86079a8a4b4e126acfbac18acfef0ee5
