### ISSUE TITLE
Remove references to provider when "Add provider name to bouquets" is enabled

### ISSUE THREAD

**Issue by Azureit** [oe-alliance/AutoBouquetsMaker#249]
When "Add provider name to bouquets" is enabled there is no need to have reference of the provider in the list
In this example, the 
`#SERVICE 1:64:0:0:0:0:0:0:0:0:` 
`#DESCRIPTION MEO - MEO`
is not needed and should be omitted, or at least an option to omit when "Add provider name to bouquets" is enabled.

And when "Add provider name to bouquets" is enabled the " - All channels"  from the NAME should be omitted too, it make sense only when the bouquet is a subset of All channels.

```
#NAME MEO - All channels
#SERVICE 1:64:0:0:0:0:0:0:0:0:
#DESCRIPTION MEO - MEO
#SERVICE 1:0:1:65:65:53:ce40000:0:0:0:
#SERVICE 1:0:1:66:65:53:ce40000:0:0:0:
#SERVICE 1:0:1:44f:65:53:ce40000:0:0:0:
#SERVICE 1:0:1:450:65:53:ce40000:0:0:0:
#SERVICE 1:0:1:177e:26:36:ce40000:0:0:0:
#SERVICE 1:0:1:69:65:53:ce40000:0:0:0:
#SERVICE 1:0:1:85:65:53:ce40000:0:0:0:
#SERVICE 1:0:1:453:65:53:ce40000:0:0:0:
#SERVICE 1:0:1:1388:30:36:ce40000:0:0:0:
#SERVICE 1:0:1:8a:65:53:ce40000:0:0:0:
#SERVICE 1:0:1:179b:2f:36:ce40000:0:0:0:
#SERVICE 1:0:1:177f:26:36:ce40000:0:0:0:
#SERVICE 1:0:1:196:68:53:ce40000:0:0:0:
#SERVICE 1:0:1:138d:30:36:ce40000:0:0:0:
#SERVICE 1:0:1:455:65:53:ce40000:0:0:0:
#SERVICE 1:320:0:0:0:0:0:0:0:0:
#DESCRIPTION  
#SERVICE 1:320:0:0:0:0:0:0:0:0:
#DESCRIPTION  
#SERVICE 1:0:1:6b:65:53:ce40000:0:0:0:
#SERVICE 1:0:1:6a:65:53:ce40000:0:0:0:
#SERVICE 1:320:0:0:0:0:0:0:0:0:
#DESCRIPTION  
#SERVICE 1:0:1:579:68:53:ce40000:0
```

**Comment by AbuBaniaz** [comment]
@noguxi  I'll close this now.

**Comment by AbuBaniaz** [comment]
The tricky thing is that not all of us have access to all the providers so testing is different. This is 

I agree `MEO-MEO`  is not good. However, that may also be contributed because the first/only section in the provider file is called MEO
```
<section number="1">MEO</section>
```
Not everybody uses the plugin the same way nor for the same providers. I always enable the provider name, others may not do so,  so for them they only see `MEO` and it makes perfect sense. They presumably do not use a combination of more than one provider which have the same names for sections. And using `All channels`  for the single section providers would conflict with what they use.

Maybe the solution is along the lines:
For providers with only one section, when provider name is added to bouquets, do not show the section name.

**Comment by AbuBaniaz** [comment]
The following is a list of providers with one section only (not complete).  The Dutch terrestrial has several files, I don't know what one looks like when the provider name is enabled.

```
<name>Canal Digitaal HD</name>
<name>Com Hem</name>
<name>Cyfrowy Polsat</name>
<name>Deutsche Sender</name>
<name>Diveo</name>
<name>HD Austria</name>
<name>NC+</name>
<name>Nova</name>
<name>Nova</name>
<name>Saorsat</name>
<name>Skylink Czech Republic</name>
<name>Skylink Slovak Republic</name>
<name>TDT Portuguesa</name>
<name>TV Vlaanderen</name>
<name>Tivusat</name>
<name>TéléSAT</name>
<name>Viasat</name>
<name>Ziggo (NL)</name>
<name>NL Terrestrial 1/5</name>
```

**Comment by AbuBaniaz** [comment]
> Maybe the solution is along the lines: For providers with only one section, when provider name is added to bouquets, do not show the section name.

Or conversely, for providers with only one section, when provider name is added to bouquets, do not show the provider name.

**Comment by AbuBaniaz** [comment]
@noguxi 
Any update on this please or ok to close?

**Comment by AbuBaniaz** [comment]
@noguxi 
Any update on this issue please?
