### ISSUE TITLE
Sky Arts

### ISSUE THREAD

**Issue by KrisDaviesw6** [oe-alliance/AutoBouquetsMaker#306]
Sky Arts seems to have stopped working when area set to London SD on Sky.

**Comment by AbuBaniaz** [comment]
It is working fine for me.  There are only two versions anyway, both on same TP. You might have a reception issue. Please check signal finder and confirm that you can receive the following transponder:
12148 MHz
Horizontal
27500
2/3

Another test is: 
Don't use ABM, use manual scan, select single satellite. You should get over 740 channels. If you don't there is an issue.

**Comment by KrisDaviesw6** [comment]
Thank you so much for your quick reply. The signal you mention above the 12148 I can receive but only on channel 1135

The channel that was working until last week, channel 130 signal is now showing 11836 MHz, Horizontal, 27500.

I haven't touched any settings for months so I am at a loss as to what has happened. 

I'm quite the novice at this so if you have any ideas and the time to spare, I would be beyond grateful for any help or explanation you could provide.

Thanks once again.

**Comment by AbuBaniaz** [comment]
The broadcaster moves the transponders being used to transmit channels. ABM keeps up with these changes. When a channel moves to a transponder people can't receive, a previous hidden/unknown issue comes to the fore. The 11836 transponder is not even listed on the the current satellites.xml file (this separate to ABM), so that transponder is not being used at the moment. 

Please do not mention channel numbers. It does not help for 28.2 and confuses matters.

Task 1.
Go into signal finder. Select the transponder that I mentioned before. Check that you can receive signal on the transponder. Post a screenshot of what you get.

Menu > Setup > Tuners & Scanning > Signal Finder
Use the up/down/left/right buttons on the remote to change options to what is pictured.
Take a screenshot and upload it.

![signal finder](https://github.com/user-attachments/assets/cd5c3f15-401e-4e68-ae87-583f69aedf21)


Task 2
Perform a single satellite scan of 28.2 and post back the results.

Menu > Setup > Tuners & Scanning > Manual scan

Use the up/down/left/right buttons on the remote to change options
Ensure you select "Single satellite"
For the purposes of this exercise, ensure you select clear before scan
How many channels do you get, post back a picture of the options you have used as well as stating the total number of channels you get at end.

![scan options 28 2 ](https://github.com/user-attachments/assets/69bbb0dd-275f-4e08-a78b-f141554ea0f5)

I got 754
![scan complete_2024_10_01](https://github.com/user-attachments/assets/31b80327-102a-46c8-b3ba-d3af42905bc6)

If you have made your own bouquets, ABM does not update/touch them. You will have to update those yourself. Reading between the lines, this is what I think you have done.

**Comment by AbuBaniaz** [comment]
If it is alright with you , I will close this issue. Feel free to post on forum if it is better so other can assist.

**Comment by KrisDaviesw6** [comment]
Hi

Sorry for the no reply a bit of an emergency at home. I shall follow your advise this evening and post back then if that is OK.

Tha ka for your continuing support.

**Comment by AbuBaniaz** [comment]
I hope everything at home works out okay.

**Comment by KrisDaviesw6** [comment]
Thank you for your concern, it's appreciated. My father had a minor stroke but is already improving so fingers crossed.

I took a picture of the signal finder for the transponder you mentioned and have attached a screenshot.

What I noticed though was that I am getting 5/6 at the end of the transponder rather than 2/3 and I can find no way of changing it to 2/3 

I also did a manual scan as you suggested and got 638 channels.

You also suggested I may have made my own bouquets. That is way above my knowledge and I have just set up ABM as normal.

I have attached the screenshots.

Once again thanks for your patience and help.


![IMG_20241006_172559](https://github.com/user-attachments/assets/e3004c8d-0cde-4a4a-bbf5-425f45a07f4d)
![IMG_20241006_171203](https://github.com/user-attachments/assets/133132c7-558d-4b27-adc3-41f5b26a9124)

**Comment by KrisDaviesw6** [comment]
I replaced the satellite.xml and the 5/6 changed to 2/3 but the problem persisted.

I have now done a full clean install and I still can't view Sky Arts on the channel provided by autoboquet maker, so I feel you may be correct in assuming my dish needs adjusting.

Once again thank you for your help and your patience. It really is appreciated.

May life treat you kindly.

**Comment by AbuBaniaz** [comment]
OK to close this issue? You will need the dish/lnb looked at.

**Comment by KrisDaviesw6** [comment]
I did a full reinstall with a point update and everything worked fine again, so I don't know what went wrong but it wasn't a dish or lnb issue.

But yes you can close this issue and thank you once again for your help.
