### ISSUE TITLE
VTI image

### ISSUE THREAD

**Issue by ikosk** [oe-alliance/AutoBouquetsMaker#74]
I use vti image and install AutoBouquetsMaker. Everything works fine, but in favorite groups are empty items from the title Separate.  It is possible to delete these groups?

**Comment by atvcaptain** [comment]
for close source image no support ask vti

**Comment by ikosk** [comment]
This problem is also with OpenATV when loading data into DreamEdit.

**Comment by AbuBaniaz** [comment]
Can you post a picture showing what you mean. Please also attach the bouquets.tv file.

Does the same thing happen with E-channelizer.

ABM also uses markers which are meant to be hidden. These markers are generic to Enigma2.

**Comment by ikosk** [comment]
![screen](https://user-images.githubusercontent.com/6972490/38550323-78ceaa7c-3cb6-11e8-82bd-4a860c918e73.png)

**Comment by Huevos** [comment]
It is because VTi does not have handling for invisible services.

https://github.com/OpenViX/enigma2/blob/Dev/lib/service/iservice.h#L47

Removing those services/bouquets will just screw with the channel numbering, and after all that is the whole point of ABM.

Your best bet is switch image to one that has all the important features built in.

**Comment by AbuBaniaz** [comment]
https://github.com/OpenViX/enigma2/blob/Dev/lib/service/iservice.h#L30:L47

ABM uses the following for the markers
```
#SERVICE 1:519:1:0:0:0:0:0:0:0:
```
This is made up of
1 `isDirectory`
+
2 `mustDescent`
+
4 `canDescent`
+
512 `isInvisible`

If we remove these, the plugin will not work as expected. For example, every provider starts at 1000, the blanks too.

Please update your image to handle the markers.
